name: 'beticon-dev'
services:
  proxy:
    container_name: 'beticon-dev-proxy'
    hostname: 'beticon-dev-proxy'
    build:
      dockerfile: './proxy/Dockerfile'
      context: .
    volumes:
      - './proxy/default.conf:/etc/nginx/templates/default.conf.template:ro'
      - './proxy/nginx.conf:/etc/nginx/nginx.conf'
    env_file:
      - './proxy/.env'
    network_mode: 'host'
    restart: unless-stopped
  service:
    container_name: 'beticon-dev-service'
    hostname: 'beticon-dev-service'
    image: docker.no1hardy.ch/noonehardy/beticon/service:develop
    ports:
      - '26001:26001'
    env_file:
      - './service/.env'
    restart: unless-stopped
  frontend:
    container_name: 'beticon-dev-frontend'
    hostname: 'beticon-dev-frontend'
    image: docker.no1hardy.ch/noonehardy/beticon/frontend:develop
    ports:
      - '26002:80'
    restart: unless-stopped
  mysql:
    container_name: 'beticon-dev-mysql'
    hostname: 'beticon-dev-mysql'
    image: mysql:8.3.0
    ports:
      - '26006:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    env_file:
      - 'mysql/.env'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: beticon
    restart: unless-stopped
  cdn:
    container_name: 'beticon-dev-cdn'
    hostname: 'beticon-dev-cdn'
    image: nginx
    volumes:
      - './service/storage:/usr/share/nginx/html:ro'
    ports:
      - '26009:80'
    restart: unless-stopped
volumes:
  mysql-data:
    name: 'beticon-dev-mysql-data'