server.port=26001
spring.application.name=service

spring.datasource.url=jdbc:mysql://${DATABASE_HOST}/wm
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PW}
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=5000000

security.jwt.secret-key=${SECRET_KEY}
security.jwt.expiration-time=3600000

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PW}

wm.participation.fee=10
wm.verification.email.validity=5
wm.verification.password_reset.validity=10
wm.host.name=${BASE_URL:https://wm.no1hardy.ch}
wm.joker.double=${JOKER_DOUBLE:10}
wm.joker.triple=${JOKER_TRIPLE:6}