name: build-docker-image
author: no1ha
description: build-docker-image
inputs:
  project:
    description: 'The project name and folder of image that is built'
    required: true
runs:
  using: composite
  steps:
    - name: 'Build docker image'
      shell: bash
      run: docker build -t wm-2026-${{ inputs.project }} -f ${{ inputs.project }}/Dockerfile .
