server {
    listen 80;

    location ~ ^\/(?!api|cdn).* {
        proxy_pass ${FRONTEND_HOST};
    }

    location ~ ^\/(?!cdn)api\/.* {
        rewrite ^/api(/.*)$ $1 break;
        proxy_pass ${BACKEND_HOST};
    }

    location ~ ^\/(?!api)cdn\/.* {
        rewrite ^/cdn(/.*)$ $1 break;
        proxy_pass ${CDN_HOST};
    }
}