name: 'Publish docker image'
author: no1ha
description: 'Publishes the docker image to https://docker.no1hardy.ch'
inputs:
  project:
    description: 'The project of the image that is published'
runs:
  using: composite
  steps:
    - name: 'Get current date'
      shell: bash
      run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    - name: 'Get image tag'
      shell: bash
      run: echo "TAG=$( echo '${{ github.sha }}' | cut -c 1-7 )-${{ env.NOW }}" >> $GITHUB_ENV
    - name: 'Tag docker image (latest)'
      shell: bash
      run: docker tag wm-2026-${{ inputs.project }} docker.no1hardy.ch/wm-2026-${{ inputs.project }}:latest
    - name: 'Tag docker image (version)'
      shell: bash
      run: docker tag wm-2026-${{ inputs.project }} docker.no1hardy.ch/wm-2026-${{ inputs.project }}:${{ env.TAG }}
    - name: 'Push docker image'
      shell: bash
      run: |
        docker push docker.no1hardy.ch/wm-2026-${{ inputs.project }}:${{ env.TAG }}
        docker push docker.no1hardy.ch/wm-2026-${{ inputs.project }}:latest
