name: Frontend
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            frontend
            gradle
      - name: Install gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: Linting
        run: ./gradlew :frontend:lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            frontend
            gradle
      - name: Install gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: Testing
        run: ./gradlew :frontend:test
  build:
    needs: [ lint, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            frontend
            gradle
      - name: 'Build docker image'
        uses: ./.github/actions/build-docker-image
        with:
          project: 'frontend'
      - name: 'Publish docker image'
        if: github.ref_name == 'develop'
        uses: ./.github/actions/publish-docker-image
        with:
          project: 'frontend'
          registry_username: ${{ secrets.DOCKER_REGISTRY_USER }}
          registry_password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}