name: Frontend
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            frontend
            gradle
      - name: Install gradle gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: Linting
        run: ./gradlew :frontend:lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            frontend
            gradle
      - name: Install gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: Testing
        run: ./gradlew :frontend:test
  build:
    needs: [ lint, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            frontend
      - name: 'Build and store docker image'
        uses: ./.github/actions/build-and-store-docker-image
        with:
          project: 'frontend'