# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint frontend

on:
  push:
  pull_request:
    branches: [ "develop" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          frontend
          gradle
    - name: Set up gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
    - name: Build gradle
      run: ./gradlew build
    - run: ./gradlew -q projects
    - name: 'Lint frontend'
      run: ./gradlew :frontend:lint
