name: Proxy
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            proxy
      - name: 'Build docker image'
        uses: ./.github/actions/build-docker-image
        with:
          project: 'proxy'
  publish:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: 'Download docker image artifact'
        uses: actions/download-artifact@v4
        with:
          name: 'wm-2026-proxy-${{ github.sha }}'
      - name: 'Load docker image'
        run: gunzip -c image.tar.gz | docker load
      - name: 'Publish docker image'
        uses: ./.github/actions/publish-docker-image
        with:
          project: 'proxy'