name: Proxy
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            proxy
      - name: 'Build docker image'
        uses: ./.github/actions/build-docker-image
        with:
          project: 'proxy'
      - name: 'Publish docker image'
        if: github.ref_name == 'develop'
        uses: ./.github/actions/publish-docker-image
        with:
          project: 'proxy'
          registry_username: ${{ secrets.DOCKER_REGISTRY_USER }}
          registry_password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}