name: Service
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            service
            gradle
      - name: Java version
        run: java -version
      - name: Get configuration
        run: echo "${{ secrets.SERVICE_CONF }}" > service/.env
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: Testing
        run: ./gradlew :service:test
  build:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            service
      - name: 'Build docker image'
        uses: ./.github/actions/build-docker-image
        with:
          project: 'service'
  publish:
    needs: [ build ]
    # if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            service
      - name: 'Download docker image artifact'
        uses: actions/download-artifact@v4
        with:
          name: 'wm-2026-service-${{ github.sha }}'
      - name: 'Load docker image'
        run: gunzip -c image.tar.gz | docker load
      - name: 'Publish docker image'
        uses: ./.github/actions/publish-docker-image
        with:
          project: 'service'